version: '3.7'
services:
    database:
        build: ./database
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment: 
            SA_PASSWORD: P@ssw0rd
            ACCEPT_EULA: Y
        volumes:
            - /var/opt/data/mssql/data/:/var/opt/mssql/data/
            - /var/opt/data/mssql/backup/:/var/opt/mssql/backup/
            - ./database/restore/:/var/opt/mssql/restore/
        ports:
            - "1433:1433"
        networks:
            arobas_network:
    
    appsrv:
        image: tomcat:6.0.48
        depends_on: 
            - database
        # ports:
        #     - "8888:8080"
        volumes:
            - ./appsrv/conf/:/usr/local/tomcat/conf
            - ./appsrv/webapps/:/usr/local/tomcat/webapps
        networks:
            arobas_network:

    proxy:
        image: httpd:2.4.41-alpine
        depends_on: 
            - appsrv
        ports:
            - "81:80"
        volumes:
            - ./proxy/conf/:/usr/local/apache2/conf/ #/tmp/pse/apache2/conf
            - ./proxy/www/:/usr/local/apache2/htdocs/ #/tmp/pse/apache2/htdocs
        networks:
            arobas_network:

networks:
    arobas_network: