version: '3.7'
services:
    database:
        build: ./database
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment: 
            SA_PASSWORD: P@ssw0rd
            ACCEPT_EULA: Y
        volumes:
            - /var/opt/data/mssql/data/:/var/opt/mssql/data/
            - /var/opt/data/mssql/backup/:/var/opt/mssql/backup/
            - ./database/restore/:/var/opt/mssql/restore/
        ports:
            - "1433:1433"
        networks:
            arobas_network:
    
    appsrv:
        image: tomcat:6.0.48
        depends_on: 
            - database
        ports:
             - "8888:8080"
        volumes:
            - ./appsrv/conf/server.xml:/usr/local/tomcat/conf/server.xml            
            - ./appsrv/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
            - ./appsrv/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
            - ./appsrv/webapps/:/usr/local/tomcat/webapps
            - ./appsrv/logs/:/usr/local/tomcat/logs
            - ./appsrv/ssl/:/usr/share/etc/ssl
            - metadata-idp:/usr/share/etc/ssl/arobas/metadata:ro
        networks:
            arobas_network:

    authsrv:
        build:
            context: ./authsrv
            args:
                SERVERNAME: $EXPOSE_PROXY_AUTH_SRV_NAME
                SCOPE: $EXPOSE_PROXY_AUTH_DOMAIN
                PROXYPORT: $EXPOSE_PROXY_AUTH_PORT                
        depends_on: 
            - appsrv
        ports:
             - "8889:8080"
        volumes:
            - ./authsrv/metadata_sp/:/opt/shibboleth-idp/metadata_sp:rw
            - metadata-idp:/opt/shibboleth-idp/shared-metadata/:rw
#            - ./authsrv/logs/:/usr/local/tomcat/logs
        networks:
            arobas_network:
              aliases:
                - idpmae.dev.diplomatie.gouv.fr

    sptest:
        build: 
            context: ./sptest
            args:
                SERVERNAME: $EXPOSE_PROXY_AUTH_SRV_NAME
                SCOPE: $EXPOSE_PROXY_AUTH_DOMAIN
                PROXYPORT: $EXPOSE_PROXY_AUTH_PORT
                SPTEST_PORT: $EXPOSE_SPTEST_PORT
        depends_on: 
            - authsrv
        volumes:
            - ./sptest/shibboleth-sp/attribute-map.xml:/etc/shibboleth/attribute-map.xml
            - ./sptest/shibboleth-sp/sp-encrypt-cert.pem:/etc/shibboleth/sp-encrypt-cert.pem            
            - ./sptest/shibboleth-sp/sp-encrypt-key.pem:/etc/shibboleth/sp-encrypt-key.pem
            - ./sptest/shibboleth-sp/sp-signing-cert.pem:/etc/shibboleth/sp-signing-cert.pem            
            - ./sptest/shibboleth-sp/sp-signing-key.pem:/etc/shibboleth/sp-signing-key.pem
            - ./sptest/appfiles:/var/www/html
            - metadata-idp:/etc/shibboleth/metadata:ro
        networks:
            arobas_network:
        ports:
            - "82:80"
            - "$EXPOSE_SPTEST_PORT:443"

    proxy:
        image: httpd:2.4.41
        depends_on: 
            - appsrv
            - authsrv
        ports:
            - "81:80"
            - "$EXPOSE_PROXY_AUTH_PORT:443"
        volumes:
            - ./proxy/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./proxy/conf/vhosts:/usr/local/apache2/conf/vhosts
            - ./proxy/conf/vhosts_secure:/usr/local/apache2/conf/vhosts_secure
            - ./proxy/conf/server.crt:/usr/local/apache2/conf/server.crt
            - ./proxy/conf/server.key:/usr/local/apache2/conf/server.key
            - ./proxy/www/:/usr/local/apache2/htdocs/
        networks:
            arobas_network:

networks:
    arobas_network:

volumes:
    metadata-idp:
