DECLARE @DB_NAME AS VARCHAR(255),
        @CURENTDATE AS VARCHAR(15),
        @RESTORE_NAME AS VARCHAR(max);

SET @DB_NAME = 'AROBAS_PRESTA';
SET @CURENTDATE = REPLACE(REPLACE(CONVERT(VARCHAR(19), GETDATE(), 127),':',''), '-', '');
SET @RESTORE_NAME = CONCAT('/var/opt/mssql/backup/',@DB_NAME,'_', @CURENTDATE, '.bak');

BACKUP DATABASE @DB_NAME
 TO DISK = @RESTORE_NAME
    WITH FORMAT;
GO
