select log_reuse_wait_desc
from sys.databases
where name = 'AROBAS_PRESTA';

SELECT name FROM sys.master_files WHERE type_desc = 'LOG'

USE AROBAS_PRESTA
ALTER DATABASE AROBAS_PRESTA
SET RECOVERY SIMPLE
GO
USE AROBAS_PRESTA
DBCC SHRINKFILE (AROBAS_log, 1)
GO
ALTER DATABASE AROBAS_PRESTA
SET RECOVERY FULL